### PR TITLE
initial stab at some tracing docs

### PR DESCRIPTION
**Pull request by pmuellr**
for issue #22 "add docs directory to repo"

### CODE REVIEW

**Comment by Qard** [comment]
LGTM

**Comment by mikeal** [comment]
This is awesome!

Is there anywhere that we are exposing these other than here? I'd like to get these viewable from the website.

**Comment by Qard** [comment]
I can help getting it into the docs repo. What are your thoughts on the progress docs state of some of this though? The trace_event.h stuff is not really usable at all yet, so I'm not sure what the value of having that on the website would be.

What *might* be interesting is to give working groups a more public-facing space to share progress and inform people what work needs to be done. People could just go digging in the github repos, but that doesn't feel quite as welcoming.

**Comment by AndreasMadsen** [comment]
AsyncWrap is specifically left out of the official documentation so that it doesn't need to obey semver.

**Comment by Qard** [comment]
Yeah, I definitely wouldn't want to put this stuff in API docs; this is all use-at-your-own-risk material. It could use more visibility though.

**Comment by pmuellr** [comment]
@mikeal I think at this point the docs aren't really designed to be public-facing; we have lots of info collected over minutes, blog posts, other conversations, and these docs are intended to be a single place to collect that stuff.

For now.

Eventually, when/if anything becomes public-facing-able, totally makes sense to add to the official docs.

**Pull request merged**
