### PR TITLE
Request to join Tracing WG

### PR DESCRIPTION
**Pull request by watson**
I've been working with errors and instrumentation in Node for a couple of years. I'd like to join the working group to be more involved with the development and improvement of the tracing api's etc within Node. I'm an experienced Node dev and have been working full time with Node since around v0.4/0.8

NPM: https://www.npmjs.com/~watson

Thanks :)

### CODE REVIEW

**Comment by bnoordhuis** [comment]
The next WG call is in 28 minutes from now so you're just in time to join.  See #24 for call details.

**Comment by AndreasMadsen** [comment]
Can he join without an invite?

**Comment by bnoordhuis** [comment]
If it's set up like the other HOAs, he can.  @pmuellr?

**Comment by watson** [comment]
@pmuellr Thanks for really interesting call. I'm really intersted in AsyncWrap @trevnorris, so hopefully I'll find some way to help with that :smiley:

**Comment by pmuellr** [comment]
Just for completeness - yes - I've done all HoA's as public, so anyone can join, will deal with "problems" if they arise.  Today's call was mistakenly created w/my personal gmail account, which only allows for 10 participants.  I'll use my company Google Apps account next time, which should allow for 15 participants.

**Pull request merged**
